version: 2.0
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:9.6-alpine

    working_directory: /home/circleci/leaflike

    steps:
      - checkout

      - attach_workspace:
          at: /home/circleci/leaflike

      - restore_cache:
          keys:
            - leaflike-{{ checksum "project.clj" }}

      - run:
          name: Download dependencies
          command: lein deps
          working_directory: /home/circleci/leaflike

      - save_cache:
          key: leaflike-{{ checksum "project.clj" }}
          paths:
            - /home/circleci/.m2

      - persist_to_workspace:
          root: .
          paths: .

  test:
    docker:
      - image: circleci/clojure:lein-2.7.1
      - image: circleci/postgres:9.6-alpine
        environment:
        - POSTGRES_USER: root
        - POSTGRES_DB: leaflike_test

    working_directory: /home/circleci/leaflike

    steps:
      - attach_workspace:
          at: /home/circleci/leaflike

      - run:
          name: copy config file for test
          command: cp /home/circleci/leaflike/resources/config/config.edn.test /home/circleci/leaflike/resources/config/config.edn
          working_directory: /home/circleci/leaflike

      - run:
          name: leaflike tests
          command: lein test
          working_directory: /home/circleci/leaflike

  build_jar:
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: /home/circleci/leaflike

    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m

    steps:
      - attach_workspace:
          at: /home/circleci/leaflike

      - run:
          name: Clean artifacts
          command: lein clean
          working_directory: /home/circleci/leaflike

      - run:
          name: Compile uberjar
          command: lein uberjar
          working_directory: /home/circleci/leaflike

      - store_artifacts:
          path: /home/circleci/leaflike/target/leaflike-0.0.1.jar
          destination: uberjar

      - run: ls /home/circleci/leaflike/target

      - save_cache:
          paths:
            - /home/circleci/.m2
          key: leaflike-{{ checksum "project.clj" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build_jar:
          requires:
            - test